vaadin.launch-browser=true
spring.application.name=gpiv

# Puerto que elegiste
server.port=8081

# --- DATOS DE CONEXION A SUPABASE ---(NUbe)
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.kldylygztvlvqtkjdugy
spring.datasource.password=yhXdrJJoW8l0GfqV
spring.datasource.driver-class-name=org.postgresql.Driver

# --- HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- CONFIGURACI�N DE GMAIL ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu-cuenta@gmail.com
# OJO: Aqu� va la "Contrase�a de Aplicaci�n" de 16 letras de Google
spring.mail.password=tu-codigo-de-16-letras 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Aumentar el limite de subida de archivos (PDFs)
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB